### ISSUE TITLE
10bit depth per channel support 

### ISSUE THREAD

**Issue by mash-graz** [scikit-video/scikit-video#109]
i couldn't figure out any solution to utilize scikit-video for accurate reading of >10bit pixel formats.
by looking into the actual code, i even found hardcoded 8bit limitations resp. data expectations.
that's a significant limitation, which makes it useless for most professional video quality control.

**Comment by beyondmetis** [comment]
I believe that the latest master includes 16 bit support. It's not built into the latest package yet I think. To use it, you just need to specify the input format correctly. What is your video format, and how are you using scikit-video?

**Comment by mash-graz** [comment]
>I believe that the latest master includes 16 bit support.

sorry -- i didn't look into the more recent changes in the git repository, but just the pip installed package. but you are right, this issue seems to be fixed already by some changes from june 2018 -- and actual ffmpeg.py code logs significant better now.
it would be really useful, if you could release an update package again to make this important changes easier accessible for a wider audience.

> What is your video format, and how are you using scikit-video?
 
just look at this [post in a color grading software forum](https://forum.blackmagicdesign.com/viewtopic.php?f=21&t=79163#p439124) and you will find some very simple introductory jupyter notebooks, where i utilized scikit-video as a very useful alternative to OpenCV, because i needed more control about the ffmpegs color handling of uncompressed v210 data in legacy AVI containers.

**Comment by beyondmetis** [comment]
Just pushed a new release with the latest code that is on master. Let me know if this helps.

**Comment by mash-graz** [comment]
thanks for this extraordinary accommodating solution!
it's a great help to me, because it's much easier to share code, which doesn't need git downloads...
THANKS!
