### ISSUE TITLE
No way to determine width or height from video.

### ISSUE THREAD

**Issue by JimmyZou** [scikit-video/scikit-video#12]
I ran the first example "Video loading" or other situations when I use "skvideo.io.vread". I found the following error. I ran on a Centos7 server with x86_64 with ffmpeg installed. Any help appreciated!

Loading only luminance channel
Traceback (most recent call last):
  File "untitled4.py", line 8, in <module>
    vid = skvideo.io.vread(filename, outputdict={"-pix_fmt": "gray"})[:, :, :, 0]
  File "/home/ulu/anaconda2/lib/python2.7/site-packages/skvideo/io/io.py", line 144, in vread
    reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
  File "/home/ulu/anaconda2/lib/python2.7/site-packages/skvideo/io/ffmpeg.py", line 117, in **init**
    raise ValueError("No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.

**Comment by beyondmetis** [comment]
In my experience, this error can be caused by one of several issues. What version of FFmpeg are you using? You can just type "ffmpeg" in the terminal to find out.

Also, what type of video are trying to load? If it's raw without a header, then ffmpeg has no way to know the width and height by itself.

**Comment by JimmyZou** [comment]
Problem solved. I installed the ffmpeg using svn. But ffmpeg svn version has been no longer updated since 2011.  I installed again according to https://ffmpeg.org. It is working now.

**Comment by xiechen0692** [comment]
> Problem solved. I installed the ffmpeg using svn. But ffmpeg svn version has been no longer updated since 2011. I installed again according to https://ffmpeg.org. It is working now.

HI, How can I install the ffmpeg from https://ffmpeg.org ?

**Comment by SungmanHong** [comment]
What is svn?
