### ISSUE TITLE
Issues with imresize at /utils/image.py

### ISSUE THREAD

**Issue by gdavila** [scikit-video/scikit-video#126]
Hi,

The code seems to have a little bug that started with commit [e6c5f89]( https://github.com/scikit-video/scikit-video/commit/e6c5f8969e58652648460259fbd46d3b05b34381).

 The imresize function used in  skvideo/utils/image.py is based on ```
 Image.fromarray(image, mode=mode).resize( (w,h),resample=PIL.Image.BICUBIC)```, but it seems that the parameters `(w,h)` are passed in the wrong order, i.e. ` (h,w)`.  

On the current code:

-  `image.shape[0]` is passed as` w` 

-  `image.shape[1]` is passed as` h`. 

However as far as I understand `numpy.shape` function, it returns ` h` for `image.shape[0]` and `w` for `image.shape[1]`, so the order should be inverted. (This is also the way the previous versions of the code were using image.shape return values)

If you make these changes, commit [4c80b74](https://github.com/scikit-video/scikit-video/commit/4c80b744ff5b6c7316aa298114dbd34ff2f69944) wouln´t be needed (unless I'm missing some previous bug).

**Comment by beyondmetis** [comment]
Ah, that's a good catch! I just committed the fix for both the bug and the test
