### ISSUE TITLE
Error while using skvideo.io

### ISSUE THREAD

**Issue by preksha12** [scikit-video/scikit-video#13]
While running the code

import skvideo.io
import skvideo.datasets
videodata = skvideo.io.vread(skvideo.datasets.bigbuckbunny())
print(videodata.shape)

I am getting error  AssertionError: Cannot find installation of real FFmpeg (which comes with ffprobe).

**Comment by beyondmetis** [comment]
Do you have ffmpeg installed? Can you post the output to running ffmpeg in
the terminal?

**Comment by preksha12** [comment]
When I am running whereisffmpeg or which ffmpeg it does not produces any output.
Is there any other method to find out if ffmpeg is installed or not?

**Comment by beyondmetis** [comment]
If "which ffmpeg" can't find ffmpeg, then scikit-video can't find it. This simply means that ffmpeg is not found by looking into the $PATH directories. If you aren't doing a local build of ffmpeg, then you should install ffmpeg through your package manager.

Have you tried (assuming you use ubuntu):
sudo apt-get install ffmpeg

For mac, there is likely a brew install option, though I'm only familiar with local installs for macs.

**Comment by preksha12** [comment]
Yes I have installed ffmpeg  in  ubuntu and in this after performing whreis ffmpeg it is giving in  usr/local/bin folder and I want to use this in my virtual environment for anaconda so what steps should I follow to transfer path  of ffmpeg to my virtual environment.

**Comment by beyondmetis** [comment]
Ah, at this time, I and @aizvorski working on merging the old scikit-video codebase in with a future release. In other words, we will include the VideoCapture function, but it's not yet included at this time.

**Comment by jigyasubagai** [comment]
how to install ffmpeg (using python 3.5 and windows os )
getting the error as 
AttributeError: module 'skvideo.io' has no attribute 'FFmpegReader'

**Comment by jigyasubagai** [comment]
hi how to install FFmpeg (python3.5 and Ubuntu 16.04 ) .
The error reads as 
reader = skvideo.io.FFmpegReader(args["input"],
AttributeError: module 'skvideo.io' has no attribute 'FFmpegReader'
please suggest

**Comment by beyondmetis** [comment]
What version of skvideo do you have installed?

**Comment by jigyasubagai** [comment]
resolved the installation , the issue was that i was not building oit from source ,thereafter i used these commands
run chmod 777 init.sh
run `sh init.sh`
it worked fine

**Comment by jigyasubagai** [comment]
thanks for help  @beyondmetis

**Comment by beyondmetis** [comment]
I don't understand where init.sh comes from, and I know that scikit-video works from the pip installation so building is only necessary when you want the latest bug fixes. I'm confused, but I'm glad you were able to fix your problem.

**Comment by YifZhou007** [comment]
I have installed ffmpeg and posted the output to running ffmpeg in the terminal: /usr/bin/ffmpeg,but my pycharm: Cannot find installation of real FFmpeg.

**Comment by beyondmetis** [comment]
Does /usr/bin/ffprobe exist?

**Comment by YifZhou007** [comment]
I have existed it .

**Comment by YifZhou007** [comment]
All of [trian_*.py] met the same question,i want modify io.py.vreader()    0.0

**Comment by beyondmetis** [comment]
You can try setting the ffmpeg path manually. Check out the documentation.
