### ISSUE TITLE
Python 2 support

### ISSUE THREAD

**Issue by dHannasch** [scikit-video/scikit-video#132]
NumPy has stopped supporting Python 2 (https://numpy.org/neps/nep-0014-dropping-python2.7-proposal.html), as have SciPy and Pillow (https://python3statement.org/). Does scikit-video still need to support Python 2?

**Comment by beyondmetis** [comment]
Good catch! I think we don’t need to support python2 in future releases. If someone needs python2, they can easily install a previous version if the latest version breaks compatibility. I think this has been a long time coming, and I get the sense that most folks these days are on python3 anyway.
