### ISSUE TITLE
Can't initialize skvideo.io.FFmpegWriter with flags  "-profile:v main -level 3.1"

### ISSUE THREAD

**Issue by illiaSkif** [scikit-video/scikit-video#135]
My final goal is to load, process and save with the same profile as the input. 
But now I want to try to force using main or baseline profile and faced with this issue:

> Traceback (most recent call last):
>   File "/home/ilia/anaconda3/envs/blurring-v2/lib/python3.7/site-packages/skvideo/io/abstract.py", line 514, in writeFrame
>     self._proc.stdin.write(vid.tostring())
> BrokenPipeError: [Errno 32] Broken pipe
> 
> During handling of the above exception, another exception occurred:
>
> Traceback (most recent call last):
>   File "/home/ilia/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/ptvsd_launcher.py", line 43, in <module>
>     main(ptvsdArgs)
>   File "/home/ilia/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 432, in main
>     run()
>   File "/home/ilia/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/old_ptvsd/ptvsd/__main__.py", line 316, in run_file
>     runpy.run_path(target, run_name='__main__')
>   File "/home/ilia/anaconda3/envs/blurring-v2/lib/python3.7/runpy.py", line 263, in run_path
>     pkg_name=pkg_name, script_name=fname)
>   File "/home/ilia/anaconda3/envs/blurring-v2/lib/python3.7/runpy.py", line 96, in _run_module_code
>     mod_name, mod_spec, pkg_name, script_name)
>   File "/home/ilia/anaconda3/envs/blurring-v2/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/ilia/dev.py", line 11, in <module>
>     writer.writeFrame(frame.astype(np.uint8))
>   File "/home/ilia/anaconda3/envs/blurring-v2/lib/python3.7/site-packages/skvideo/io/abstract.py", line 519, in writeFrame
>     raise IOError(msg)
> OSError: [Errno 32] Broken pipe
> 
> FFMPEG COMMAND:
> /usr/bin/ffmpeg -y -pix_fmt bgr24 -f rawvideo -s 1280x720 -i - -c:v libx264 -preset medium -r 20 -profile:v main -level 3.1 /home/ilia/test.mp4
> 
> FFMPEG STDERR OUTPUT:
> 

**Reproducer:**
```
import skvideo.io  
import cv2
import numpy as np
reader = cv2.VideoCapture('/home/ilia/video.mp4') #  h.264 encoded
writer = skvideo.io.FFmpegWriter('test.mp4', inputdict={'-pix_fmt':'bgr24'},
        outputdict={'-c:v': 'libx264','-preset': 'medium', '-r': '20','-profile:v':'main', '-level': '3.1'})
while (True):
    has_frame, frame = reader.read()
    if not has_frame:
        break
    writer.writeFrame(frame.astype(np.uint8))
```
This code produces message above

**Comment by beyondmetis** [comment]
Can you set verbosity=10 in the setup call to FFmpegWriter and report the extra output? It seems that FFmpeg has an issue, but the messages are being silenced.

**Comment by illiaSkif** [comment]
I get additional information with verbosity=10

> x264 [error]: main profile doesn't support 4:4:4
> [libx264 @ 0x55ee76117a20] Error setting profile main.
> [libx264 @ 0x55ee76117a20] Possible profiles: baseline main high high10 high422 high444
> Error initializing output stream 0:0 -- Error while opening encoder for output stream #0:0 - maybe incorrect parameters such as bit_rate, rate, width or height
> Conversion failed!

**Comment by illiaSkif** [comment]
Thanks a lot I add '-pix_fmt': 'yuv420p' to the outputdict and it fix my issue.

**Comment by illiaSkif** [comment]
Can I use another  '-pix_fmt' for baseline or main? Do you know how it could affect video quality?

**Comment by beyondmetis** [comment]
For reference, you can check out https://en.wikipedia.org/wiki/Chroma_subsampling

It really depends on application for most setting changes. Generally, yuv420p is best for compatibility with most video players and usually doesn't look horrible. However, luminance is compressed to to [16-239] instead of [0-255]. If you want the full 8bit range, you must use yuvj420p. If you want a larger bit range, I think you can explore yuv420p16 or even yuv444p16 to avoid chroma subsampling.

**Comment by illiaSkif** [comment]
Thanks a lot. I thinks my issue isn't a bug. It is an FFmpeg specific. So I close the issue.
