### ISSUE TITLE
video write seems to be hanging

### ISSUE THREAD

**Issue by cchacons** [scikit-video/scikit-video#14]
Hello, 

I'm trying to do a video write but it is hanging. I tried to follow the examples: rawsnippet.py and also ran the test suite, which hanged on the skvideo.tests.test_ffmpeg.test_FFmpegWriter ...

I'm using:
Python 2.7.12 :: Anaconda 4.1.1 (x86_64)
Macbook
scikit-video: latest code from github

Appreciate the help. 

Thanks,
Carlos

**Comment by cchacons** [comment]
After killing the process with "control + C" the following showed up:

^C^CTraceback (most recent call last):
  File "rawsnippet.py", line 17, in <module>
    skvideo.io.vwrite(filename_yuv, vid)
  File "//anaconda/lib/python2.7/site-packages/sk_video-1.1.6-py2.7.egg/skvideo/io/io.py", line 64, in vwrite
    writer.writeFrame(videodata[t])
  File "//anaconda/lib/python2.7/site-packages/sk_video-1.1.6-py2.7.egg/skvideo/io/ffmpeg.py", line 439, in writeFrame
    self._proc.stdin.write(vid.tostring())
KeyboardInterrupt


Thanks,
Carlos

**Comment by beyondmetis** [comment]
What version of ffmpeg are you using?
