### ISSUE TITLE
Too many spawned processes with vread

### ISSUE THREAD

**Issue by amlankar** [scikit-video/scikit-video#17]
I'm reading multiple videos in a loop using vread

for file_name in VIDEO_LIST:
    frames = skvideo.io.vread(file_name)
    # Process

I am reading >10000 videos, and after around 2000 videos my process starts giving an error. When I checked htop in between, I saw ffmpeg processes alive for many videos that had already been processed.

Is this a bug with skvideo not closing the underlying ffmpeg process?

EDIT:

I went through the code and I see that in io.py, an FFmpegReader object is created which spawns a subprocess, but the subprocess is never terminated after vread() is done reading the frames. So, I guess the issue is with cleanly killing the subprocess associated with the FFmpregReader object once the job's done.

**Comment by beyondmetis** [comment]
It looks like you are right. The vread/vreader functions don't close the ffmpeg process after they finish.

I just now pushed an update which should fix this. Let me know if you still have issues, and we will continue to debug.

**Comment by amlankar** [comment]
Works now :)
Thanks!

**Comment by amlankar** [comment]
Another little thing, I didn't want to open a new issue for this, the Contributing guidelines link in README points to a non-existent file, I guess it hasn't been changed since you moved to a new github account for sk-video

**Comment by beyondmetis** [comment]
I think I found the problem. It was pointing to my fork of the project and not actual main project. Is there anything else I missed?

Thanks!
