### ISSUE TITLE
AssertionError: Cannot find installation of ffmpeg, windows 7

### ISSUE THREAD

**Issue by guruvyasa** [scikit-video/scikit-video#22]
I am running a simple program using scikit-video but getting this error. I have ffmpeg installed. I can use it from command line. This is what i get when i type ffmpeg from cmd.
![screenshot](https://cloud.githubusercontent.com/assets/7962656/23093526/2f026826-f60c-11e6-8aa8-7f4685a2e5c6.png)

**Comment by beyondmetis** [comment]
This is possibly related to #21 in that the where/which command used is not compatible with Windows.

**Comment by guruvyasa** [comment]
I managed to easily solve this issue using the suggestion from [#21](https://github.com/scikit-video/scikit-video/issues/21). I used where module. I did not face any issues. Here is what i did, in skvideo/__init__.py
 ` _FFMPEG_PATH = where.where("ffprobe")[0]`
and the in the function setFFmpegPath,
   ```
 if os.name == 'nt':
        extension = '.exe'
 else:
        extension = ''
    
 if os.path.isfile(os.path.join(_FFMPEG_PATH,'ffmpeg'+extension)) and os.path.isfile(os.path.join(_FFMPEG_PATH ,"ffprobe"+extension)):
        _HAS_FFMPEG = 1
```

**Comment by ajaytomgeorge** [comment]
One of the reasons is not configure correctly, 

- **Step1:** check ffmpeg is accessible from **cmd**, type _ffmpeg_ in command line and see if it recognizes the command, if not download and unzip and add it to the _environment variable_ **path** Eg:- `D:\ffmpeg-20170125-2080bc3-win64-static\ffmpeg-20170125-2080bc3-win64-static\bin`

- **Step 2**:  Use `where ffmpeg ` in command line sometimes it could be pointing to wrong file, in my case _imageMagick_ was installed, and system was referring to that `C:\Program Files\ImageMagick-7.0.8-Q16\ffmpeg.exe`, either delete imageMagick path or put it after `D:\ffmpeg-20170125-2080bc3-win64-static\ffmpeg-20170125-2080bc3-win64-static\bin`

- **Step 3**. Close the terminal and reopen and check "where ffmpeg", dont worry if it shows two path, but the first path should be of our installation `ffmpeg-20170125-2080bc3-win64-static\ffmpeg-20170125-2080bc3-win64-static\bin`

if its okae, you are good to go
