### ISSUE TITLE
Closing FFmpegReader file

### ISSUE THREAD

**Issue by Atcold** [scikit-video/scikit-video#23]
I am unable to understand how to close a `FFmpegReader` object.
I have **many** videos, and I have to free resources, when they are not used.
Any suggestion? The `_close()` method does not really work.

I see that the `FFmpegReader.nextFrame()` iterator can be closed, but not the main object.

**Comment by beyondmetis** [comment]
Can I get an example snippet of how you are using FFmpegReader? From your problem, I assume you are calling FFmpegReader over and over in a loop.

**Comment by Atcold** [comment]
Hmm... Let me come up with a simple set up.
I have 500 videos which file name are stored in a `videos` list.
At time index `0` I need to return the first frame of all 500 videos.
At time index `1` I need to return the second frame, and so on.

**Comment by beyondmetis** [comment]
With each FFmpegReader, a subprocess of FFmpeg is spawned. Right now, the FFmpegReader holds this process and the iterator itself is just a way to communicate with this subprocess. There is no way to de-allocate FFmpegReader while still using the subprocess that it owns.

**Comment by Atcold** [comment]
Ouch! So... am I f***ed?

**Comment by beyondmetis** [comment]
Well, are you creating all your FFmpegReaders first before creating any iterators?

**Comment by Atcold** [comment]
:flushed: that was the first thing I did... yes. Then I've used `ffprobe` to get some stats instead.
Now I'm going to create iterators on demand, and hence lazily instantiate the `FFmpegObject`.

**Comment by beyondmetis** [comment]
Creating all the FFmpegReaders first minimizes the memory copied through the underlying os.fork. Since you're still having problems, you might need to get more memory or devise some other solution. Good luck!

**Comment by Atcold** [comment]
I'm not sure I understood whether I can close the `FFmpegReader` object once I'm done with its iterator.

**Comment by beyondmetis** [comment]
You should be able to close the FFmpegReader once you 100% done using its iterator. The memory should then be freed up and the ffmpeg subprocess terminated. However, if you have 500 videos that you opening (assuming you are storing results in an array), each time you open FFmpegReader, the memory required for the os.fork grows. At some point, you will have half your memory used by your program, and you will be out of memory for the FFmpegReader. This is a stupid problem related to os.fork.

**Comment by Atcold** [comment]
OK. I didn't get how I am supposed to cloase the `FFmpegReader`, though.

```python
reader = FFmpegReader('my_video.mp4')
my_iter = reader.netFrame()
my_iter.close()  # works
reader._close()  # does NOT work
```

**Comment by beyondmetis** [comment]
You should be able to close the reader. That's exactly how the vread function is implemented here: https://github.com/scikit-video/scikit-video/blob/master/skvideo/io/io.py

**Comment by Atcold** [comment]
Alright, I've been using a `reader()` object.
Let's say I've iterated through it several time, and now I'm done. Is there a nice way to just exhaust it, so that a `FFmpegReader._close()` is issued?

**Comment by beyondmetis** [comment]
There is currently nothing in place for that. A __del__ destructor should be implemented in FFmpegReader/FFmpegWriter first (which calls _close()), then I'd expect you could use a python context to scope your iterator.

**Comment by Atcold** [comment]
I see. I guess I'll end up using `FFmpegReader` object, and deal with its closure myself.
About the main topic of this issue (thank you, btw, for your invaluable assistance in off-topic quirks), although I can still access a closed `FFmpegReader` object, I can no longer iterate though it, indicating that resources have been freed. So

> OK. I didn't get how I am supposed to cloase the `FFmpegReader`, though.
> 
> ```python
> reader = FFmpegReader('my_video.mp4')
> my_iter = reader.netFrame()
> my_iter.close()  # works, I cannot call next() on it
> reader._close()  # does NOT work
> ```

works fine, and it was my poor understanding that made me open this issue, which I am now closing.

**Comment by Atcold** [comment]
My IDE is complaining when I use the private method `FFmpegReader._close()`... because private.
What is the reason behind not using simply `close()` instead?

**Comment by beyondmetis** [comment]
We should probably change in light of your experience. There's not a good reason to keep it private, unless we wanted to discourage direct usage in favor of python contexts.
