### ISSUE TITLE
vread error on image files

### ISSUE THREAD

**Issue by chenglinzhang** [scikit-video/scikit-video#24]
skvideo.io.vread raises a TypeError on image files.  Example code:

import skvideo.io
vid = skvideo.io.vread("vid_luma_frame1.png")

Environment: python 3.5.2 and ffmpeg version 2.8.11 built with gcc 5.4.0 on ubuntu 16.04

Exception trace:

/usr/local/lib/python3.5/dist-packages/skvideo/io/io.py in vread(fname, height, width, num_frames, as_grey, inputdict, outputdict, backend, verbosity)
    142             outputdict['-pix_fmt'] = 'gray'
    143 
--> 144         reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
    145         T, M, N, C = reader.getShape()
    146 

/usr/local/lib/python3.5/dist-packages/skvideo/io/ffmpeg.py in __init__(self, filename, inputdict, outputdict, verbosity)
    192             # grabbing number of frames using ffprobe
    193             probecmd = [_FFMPEG_PATH + "/ffprobe"] + ["-v", "error", "-count_frames", "-select_streams", "v:0", "-show_entries", "stream=nb_read_frames", "-of", "default=nokey=1:noprint_wrappers=1", self._filename]
--> 194             self.inputframenum = np.int(check_output(probecmd).split('\n')[0])
    195 
    196         # Create process

TypeError: a bytes-like object is required, not 'str'

**Comment by beyondmetis** [comment]
Ah, I'll look into this later, but it looks like you found a bug. Scikit-video has not been thoroughly tested with image files, but it should be since FFmpeg can handle them.

**Comment by chenglinzhang** [comment]
Python 2.7 works fine. Python 3.6 shows the same error as Python 3.5.

**Comment by beyondmetis** [comment]
This makes sense since raw data streams are handled differently between python 2 and python 3.

**Comment by zacharynevin** [comment]
@beyondmetis What is the ETA on this bug?

**Comment by beyondmetis** [comment]
@zacharynevin I'm not sure. I'm spending 100% of my time preparing for my PhD qualifying exam. I'm open to merging pull-requests

**Comment by beyondmetis** [comment]
Fixed the problem.
