### ISSUE TITLE
TypeError: 'float' object cannot be interpreted as an integer when using blockMotion in Python3

### ISSUE THREAD

**Issue by GarrettBeatty** [scikit-video/scikit-video#28]
import skvideo.io
    from skvideo.motion import blockMotion
    video = skvideo.io.vread(file)
    motion = blockMotion(video)

gives me the following error

**File "main.py", line 47, in compute_motion_vectors
    motion = blockMotion(video)
  File "/usr/lib/python3.5/site-packages/skvideo/motion/block.py", line 950, in blockMotion
    motionData = np.zeros((numFrames - 1, height / mbSize, width / mbSize, 2), np.int8)
TypeError: 'float' object cannot be interpreted as an integer**

This error does not occur when using Python2. I believe the issue is because of [this](http://stackoverflow.com/questions/37122020/what-does-float-object-cannot-be-interpreted-as-an-integer-mean-and-how-can) difference between Python versions.

**Comment by beyondmetis** [comment]
Actually, I fixed up a lot of those issues recently in the git repo, which are possibly missing in the latest packaged release of scikit-video. Let me know if you are using the pip version of scikit-video or the latest git repo version.

**Comment by GarrettBeatty** [comment]
I was using the pip release.  I tried downloading the git repo version and the problem seems to be fixed there.
