### ISSUE TITLE
Skip ahead in video

### ISSUE THREAD

**Issue by zacharynevin** [scikit-video/scikit-video#30]
Hello,

How do you skip ahead a certain number of frames in the `vreader` function? I see in the documentation that there is a `num_frames` parameter, but what if I want to do this:

- Read 500 frames from `0s`.
- Read another 500 frames from  after frame number `1000`?

The reason I am asking is because I have a set of processes in AWS Batch that are designed to process different parts of a video in parallel. Ideally I would have each batch task processing a segment of the video. When I am creating the tasks, I can specify the "limit" and "skip" (or whatever the equivalent names are here) parameters based on the video metadata.

Thanks so much

**Comment by beyondmetis** [comment]
You can use inputdict arguments, with the key '--start_number' for the starting frame offset. I did not test this, but you might be able to use something like:

rdr1 = skvideo.io.vreader(fname, inputdict={'--start_number': '0', '-vframes': '500'})

rdr2 = skvideo.io.vreader(fname, inputdict={'--start_number': '500', '-vframes': '500'})
