### ISSUE TITLE
pictures are very blurry and objects are quadrupled

### ISSUE THREAD

**Issue by identidata** [scikit-video/scikit-video#40]
I used the following code to extract frames:

    import skvideo.io
    video = 'bobby_3.mov'

    reader = skvideo.io.FFmpegReader(video)

    i = 0
    for frame in reader.nextFrame():
        cv2.imwrite('frame_2_'+str(i)+'.jpg',frame)
        i +=1

this is how a frame looks 

![image](https://user-images.githubusercontent.com/26857272/26860363-f9dc2558-4b13-11e7-822a-83a2ae4a520f.png)

I assume we need to fine tune a ffmpeg parameter, but not sure which ones (of course, I would also need to change RGB to BGR, but that is easy since based on the metadata, I know I must tune that). 

If you look at the video on any video player, it looks just fine, medium resolution. 

**Did you come across such issue and know how to fix it?**

Thanks so much.
Alejandro

**Comment by beyondmetis** [comment]
I have never observed this problem with scikit-video before. It seems like some video metadata could be  wrong? I ran your code using a random video I have on-hand, and I see the correct results. Let me know what you find out.

**Comment by identidata** [comment]
thanks for the prompt response Todd. Not sure, the video was created on an iphone mobile. Weird is, if I use older version of skvideo (e.g. code below) it does not get that effect. 

    import skvideo.io
    video = 'bobby_3.mov'
    cap = skvideo.io.VideoCapture(video)
    for i in range (0,10):
        stat, frame = cap.read()
        cv2.imwrite('whatever.jpg',frame)

Problem is, images are rotated 90 degrees counterclockwise. Problem is, I do not get access to the metadata in the older version so I do not know when I need to rotate the images and/or do a transformation from RGB to BRG.

**Or is there a way to read the metadata using the old version?**

Thanks so much again. Below a pic of how a frame looks with the older version, that I can manage pretty well if I get access to the metadata.

![image](https://user-images.githubusercontent.com/26857272/26860731-ef133074-4b15-11e7-84ff-248cc8dd7e59.png)

Btw, will report back when I find out what is going on.

**Comment by beyondmetis** [comment]
Can you provide a sample video? This is really strange that the older scikit-video works where the newer one does not. I've tested scikit-video on thousands of videos, so I'm dying to know what happened on this one.

The older version hasn't been updated in a couple years (aside from changing the license). We are probably better off just fixing the latest version, which has been tested thoroughly.

**Comment by identidata** [comment]
sure thing. but I can't upload. format not supported. feel free to shoot me an email at alejandro@identidata.io and I will send you a couple of videos (one .mov from ios and one .mp4 from android). both look the same when you capture the frames.

**Comment by beyondmetis** [comment]
I just pushed a fix for the problem. Please let me know if there are any videos that still exhibit this problem :)

**Comment by identidata** [comment]
thanks so much Todd. awesome fix, record time. you guys rock.
