### ISSUE TITLE
Use skvideo.io.ffmpeg to make a video which can be played on mobile

### ISSUE THREAD

**Issue by s885219s** [scikit-video/scikit-video#47]
Hi, me again.

Now, I am trying to put my video, created from images, online.

I use skvideo.io.ffmpeg to produce the video and  use '-vcodec': 'libx264' in outputdict, and it plays well on the PC browsers. 

However, it can not play on my cell phone(using chrome or safari), how can I fix this problem?

BTW, at first, I thought it was a decoding problem, so I have tried setting up some commands in outputdict, such as 'profile:v : high' and 'level : 4.0'.

But I got some errors below. 

> OSError: [Errno 32] Broken pipe
> 
> FFMPEG COMMAND:
> C:\path/ffmpeg.exe -y -f rawvideo -r 15 -s 500x333 -pix_fmt rgb24 -i - -profile:v high -level 4.0 -pix_fmt yuv420p -c:v h264 -b 30000000 D:\path\filename.mp4
>

**Comment by beyondmetis** [comment]
Thanks for continuing to use scikit video :) 

For cellphone playback, you can try .3gp containers. I remember having to use that over .mp4, but I'm not sure why. As for your second problem, I will see if I can reproduce this later.

**Comment by s885219s** [comment]
Oh, I got it!
The width and height of the images can not divided by 2 is the reason why I got errors from `vwrite` or `FFmpegWriter`.

And now the video is playing fine on my mobile browser.
Thanks a lot.

**Comment by beyondmetis** [comment]
That's awesome. Glad you figured it out!
