### ISSUE TITLE
Cannot vread a second video (ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.)

### ISSUE THREAD

**Issue by n17r4m** [scikit-video/scikit-video#54]
I am having difficulty loading a second video using skvideo.io.vread  

Please see the following iPython session. The first video loads successfully, however subsequent videos fail to load:

```
$ ipython3
Python 3.6.2 (default, Sep 14 2017, 18:08:00) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from skvideo import io

In [2]: %time v = io.vread("test.x265.10.mp4")
CPU times: user 10.5 s, sys: 12 s, total: 22.5 s
Wall time: 33.6 s

In [3]: %time v2 = io.vread("test.x265.10.mp4")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<timed exec> in <module>()

~/.pyenv/versions/3.6.2/envs/general/lib/python3.6/site-packages/skvideo/io/io.py in vread(fname, height, width, num_frames, as_grey, inputdict, outputdict, backend, verbosity)
    142             outputdict['-pix_fmt'] = 'gray'
    143 
--> 144         reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)$ ipython3
Python 3.6.2 (default, Sep 14 2017, 18:08:00) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from skvideo import io

In [2]: %time v = io.vread("test.x265.10.mp4")
CPU times: user 10.5 s, sys: 12 s, total: 22.5 s
Wall time: 33.6 s

In [3]: %time v2 = io.vread("test.x265.10.mp4")
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<timed exec> in <module>()

~/.pyenv/versions/3.6.2/envs/general/lib/python3.6/site-packages/skvideo/io/io.py in vread(fname, height, width, num_frames, as_grey, inputdict, outputdict, backend, verbosity)
    142             outputdict['-pix_fmt'] = 'gray'
    143 
--> 144         reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
    145         T, M, N, C = reader.getShape()
    146 

~/.pyenv/versions/3.6.2/envs/general/lib/python3.6/site-packages/skvideo/io/ffmpeg.py in __init__(self, filename, inputdict, outputdict, verbosity)
    128             self.inputheight = np.int(viddict["@height"])
    129         else:
--> 130             raise ValueError("No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.")
    131 
    132         # smartphone recordings seem to store data about rotations

ValueError: No way to determine width or height from video. Need `-s` in `inputdict`. Consult documentation on I/O.
```

Python 3.6
skvideo 1.1.8
ffmpeg version git-2017-09-27-c1f22c2 (although I have tried other versions as well)

Any ideas?

**Comment by beyondmetis** [comment]
What is the full shape of the video you are loading? I've seen similar
problems when loading a video that then occupies half of my working ram.
When running the second vread, scikit video executes a fork for ffmpeg
which copies the memory overhead that you had at the time. That fork will
fail if you don't have the memory. Given how long your vread takes, this
would be my guess

**Comment by n17r4m** [comment]
The shape of the videos in question are indeed rather large,
v.shape == (1349, 1729, 2336, 3), dtype = uint8.
A rough estimate then, is the loaded video is using in the neighbourhood of 15Gb, which is confirmed by `ps` stating about 16Gb is in use. Since my system has 32Gb of ram, I believe your hypothesis makes sense. 

However, It's interesting that os.Popen in turn runs os.execvp, which in turn runs an underyling fork() syscall, which should mmap / copy on write the heap until the exec() syscall is called to transfer the running processes over to ffmpeg. I would have thus expected ffmpeg to successfully launch and then eventually receive a MemoryError in the parent process while frame data was being streamed from the child process. *shrugs* Anyways, thanks for the insight. We're moving to a machione with more ram soon, I'll try and remember to update this issue if/when more ram solves the problem.

**Comment by beyondmetis** [comment]
The errors related to not knowing width or height from your video is a symptom of not being able to run ffprobe because of the necessary fork. 

I tried to fix forking-related issues once by implementing a fork server, but I had strange problems with unit testing so I never committed those changes. I should revisit this idea since python 3 includes built in support for fork servers.

**Comment by n17r4m** [comment]
Update: it was an issue with running out of system memory. Thanks for the hints, we've upgraded to a new system that has oodles of ram. however, there is a new issue ( #60 ) that may be caused by using a more recent ffmpeg release? Anyways, I'm closing this issue. Having a fork server or other solution to allow many videos to be read in without exploding ram would be useful though.
