### ISSUE TITLE
issue trying to set "-vsync" in outputdict (trying to use with "-vf": "select='eq(pict_type,PICT_TYPE_<X>)'")

### ISSUE THREAD

**Issue by smxzehvb** [scikit-video/scikit-video#59]
Hi-
I'm using python 2.7

I'm trying to set the outputdict parameters for skvideo.io.vreader to extract e.g. only I-frames.

This is my test video:
https://www.youtube.com/watch?v=q1mAGQAw3Oc&t=22s
The version downloaded to my machine has 64 I-frames and 3269 P-frames.

The following will run, but seems to default to "cfr" as the "-vsync" parameter (Frames will be duplicated and dropped to achieve exactly the requested constant frame rate).

iframes = skvideo.io.vreader(myvideofile, outputdict={"-pix_fmt": "gray", "-vf": "select='eq(pict_type,PICT_TYPE_I)'"}) 
k=0
for frame in iframes:
    k+=1
print k
> 3333

I want the above to yield only those 64 I-frames.

compare to:
allframes = skvideo.io.vreader(myvideofile, outputdict={"-pix_fmt": "gray"}) 
k=0
for frame in iframes:
    k+=1
print k
> 3333

Trying to set "-vsync" to "vfr"  (or anything other than "cfr") results in a RuntimeError. 

iframes = skvideo.io.vreader(myvideofile, outputdict={"-pix_fmt": "gray", "-vf": "select='eq(pict_type,PICT_TYPE_I)'", "-vsync": "vfr"})
k=0
for frame in iframes:
    k+=1
print k

RuntimeError                              Traceback (most recent call last)
<ipython-input-124-82a23ec122d0> in <module>()
      1 k=0
----> 2 for frame in vid_p:
      3     k+=1
      4 
      5 print k

/usr/local/lib/python2.7/dist-packages/skvideo/io/io.pyc in vreader(fname, height, width, num_frames, as_grey, inputdict, outputdict, backend, verbosity)
    251         reader = FFmpegReader(fname, inputdict=inputdict, outputdict=outputdict, verbosity=verbosity)
    252         try:
--> 253             for frame in reader.nextFrame():
    254                 if as_grey:
    255                     yield vshape(frame[:, :, 0])

/usr/local/lib/python2.7/dist-packages/skvideo/io/ffmpeg.pyc in nextFrame(self)
    291         """
    292         for i in range(self.inputframenum):
--> 293             yield self._readFrame()
    294 
    295 

/usr/local/lib/python2.7/dist-packages/skvideo/io/ffmpeg.pyc in _readFrame(self)
    275         # Read and convert to numpy array
    276         # t0 = time.time()
--> 277         s = self._read_frame_data()
    278         result = np.fromstring(s, dtype='uint8')
    279 

/usr/local/lib/python2.7/dist-packages/skvideo/io/ffmpeg.pyc in _read_frame_data(self)
    269             self._terminate()
    270             err1 = str(err)
--> 271             raise RuntimeError("%s" % (err1,))
    272         return arr
    273 

RuntimeError:

**Comment by beyondmetis** [comment]
This is probably a similar error to #56, in that the number of frames must be predetermined to know how many frames ffmpeg will return. Since you are asking for only I-frames, this means we need to know how many I-frames will be returned by ffmpeg. Perhaps the total number of frames can be manually overided, but that would place a burden on the user to specify the number of frames in these edge cases.

**Comment by smxzehvb** [comment]
Hmmm, ok I see what you are saying. 

I'll play with it and see if I can't come up with some kind of wrapper for vreader.
