### ISSUE TITLE
upload on conda-forge

### ISSUE THREAD

**Issue by carlodri** [scikit-video/scikit-video#61]
I would be interested in having this package on [conda-forge](https://conda-forge.org/). I can also try to build the recipe myself, unless someone is already tackling the problem. Let me know if you agree, and I can proceed.

**Comment by beyondmetis** [comment]
Sure, if this makes it easier to use, that would be great. Do we need to tag the latest code and release? I know a couple bug fixes have been implemented since the latest official version. Let me know how I can help.

**Comment by carlodri** [comment]
> Do we need to tag the latest code and release? 

yes, I think it would be better. I still have to learn how conda-forge works, but I think it's quite straightforward.

By the way: on PyPi there seems to be a `scikit-video` (outdated) and a `sk-video` package (the current one): it would be nice to "merge" the two things and come up with a single, `scikit-video` package which follows the standard `scikit` naming scheme.

**Comment by beyondmetis** [comment]
I contacted Alex, one of our contributers responsible for the merge process between scikit-video and sk-video, but I haven't heard from him in over a year.

In the meantime, I'll update the tag on sk-video.

Do we have to actively maintain the latest release on conda-forge? Or is this automatic?

**Comment by beyondmetis** [comment]
Tag updated

**Comment by carlodri** [comment]
> Do we have to actively maintain the latest release on conda-forge? Or is this automatic?

no, versions on conda-forge must be manually bumped

**Comment by carlodri** [comment]
as far as I understand, I think I need also the tar.gz source package on PyPi: is this possible? How do you manage the PyPi uploading? do you do it by hand?

**Comment by beyondmetis** [comment]
I do it by running a console command, which builds the wheel and uploads the package to pypi. Let me see if I can build a source package.

**Comment by beyondmetis** [comment]
Alright, it looks like the source build worked. Try it now?

**Comment by carlodri** [comment]
ok I can see it, thanks. Now I need to prepare the conda recipe, it will take me some time to figure out the right setup. Probably I will bother you with other questions...

**Comment by carlodri** [comment]
ok, I have staged a very basic recipe and the tests are green (see [here](https://github.com/conda-forge/staged-recipes/pull/4587). Since you are using a BSD license I think you should include the `LICENSE` file with the license full text.

Now we need to wait for the PR to be reviewed and included in the conda-feedstock. If you wish, (@beyondmetis) I can add you as a maintainer of the conda-feedstock as well.

**Comment by carlodri** [comment]
ok @beyondmetis, thanks for uploading the license text. Can you re-upload the tar.gz including the LICENSE.txt file? Or are you forced to bump the version number?

**Comment by beyondmetis** [comment]
I tried to re-upload the updated tar.gz file, but pypi never allows file replacement. I will bump the version and re-upload.

**Comment by beyondmetis** [comment]
Version has been bumped with license file.

**Comment by carlodri** [comment]
@beyondmetis package is now live on `conda-forge`, this is the [link to the feedstock](https://github.com/conda-forge/sk-video-feedstock).

One possible quirk is the following: I have inserted the [`ffmpeg` `conda` package](https://github.com/conda-forge/ffmpeg-feedstock) among the build dependencies, which means that installing the package will automatically install also the `ffmpeg` package. On second thought, I'm quite sure that not all users want an automated install of the latter: _e.g._ a scenario where the user has his/her own `ffmpeg` installation or wants to use `libav`. Do you agree? Should I remove this dependency?

**Comment by beyondmetis** [comment]
You can remove the ffmpeg dependency since skvideo checks for a working ffmpeg/libav install. Installing isn't totally automatic, but at the least the user will see the right error if the dependency is not met.

It looks like we will transition the sk-video package to scikit-video on pypi soon. We would probably update both pypi names for a period of time. How hard is it to update the conda package to point to scikit-video on pypi when this happens?

**Comment by carlodri** [comment]
> You can remove the ffmpeg dependency

done.

> How hard is it to update the conda package to point to scikit-video on pypi when this happens?

no idea.... let's say that we can close this issue and we open another one when the transition starts happening. Agreed?

**Comment by beyondmetis** [comment]
Agreed
