### ISSUE TITLE
sk-video 与 scikit-video both exists in PYPI, and same module name

### ISSUE THREAD

**Issue by oneTaken** [scikit-video/scikit-video#62]
I want to use `skvideo` to replace opencv temporary.

And I found `sk-video` and `scikit-video`, which can be installed by
`pip install sk-video` and  `pip install scikit-video` respectivly.
And after installed, the python module is the same.
```
import skvideo
```
It's really confusing.

**Comment by beyondmetis** [comment]
I've already emailed @aizvorski about this. He hasn't responded.

**Comment by oneTaken** [comment]
Thanks for your quick reply.
By the way, I am a master candicate from China.
I  got your are a PHD on I&VQA just now. Great GPA.
 I did some research about IQA for a short time. 

And I am doing something about video question answer recently. And I have a subtask to confirm the video coherent, a video may be made up many small videos. I use `SSIM`  and a threshold to confirm the video is from the same small video or not. It's not good enough.
Do you have any idea to better solve this?
Thanks so much.

**Comment by beyondmetis** [comment]
I'm not sure exactly what you mean. A video may be made up of many small videos? Do you mean videos with different scenes, or do you mean finding a video clip inside the original video?

**Comment by oneTaken** [comment]
The subtask is more similar to the latter description.
Due to the dirty dataset, a video may be made up of many sub videos, which are different.

For example:
For something to do about films, the video in the dataset may have this video:
many clips from different films make up a new video. And the new video is what I have.

I have to pick up these different film clips from the video. SSIM is not good enough.

**Comment by beyondmetis** [comment]
Well, if you already have the clip that you interested in finding within the new video, you can just use mean squared error (MSE) or sum of absolute differences (SAD). In other words, the clip is your template, and you want to correlate it against the new video. The correlation will be highest when mean squared error is lowest.

**Comment by oneTaken** [comment]
I have tried `MSE`, but not `SAD`. I will have a try to know whether useful.
The `MSE` result is really rough.
I don't know how many images are from the same clip, and I don't have clips. I only have the new video.

Images may have low mse value, and they are from different clips.
SSIM has a better result, but not good enough.

**Comment by beyondmetis** [comment]
It sounds like I completely misunderstood your problem. You can try a scene detector to split the clips in the new video. There is one already in sk-video.

**Comment by alex-at-thimble** [comment]
@beyondmetis I added you to the scikit-video pypi as maintainer so you can go ahead and change the info over to point here and upload the latest release.  I'll open a separate issue for a few cleanup things that we'll have to do around that - I think not blocking.

**Comment by oneTaken** [comment]
I saw the api. I'll have a try for this.
Actually, before SSIM, I use the `key-frame ` to roughly detect small clips.
And then use SSIM to merge this rough clips. Obviously, SSIM is not enough to clip.

**Comment by beyondmetis** [comment]
@alex-at-thimble Thanks! I'll need to make a few updates to documentation as well, which should not be a big deal.

**Comment by beyondmetis** [comment]
I've pushed the current version of sk-video into pypi as scikit-video. @oneTaken if you'd like to take this unrelated conversation offline, you can always email me directly.
