### ISSUE TITLE
FFMpegReader input and output dict format

### ISSUE THREAD

**Issue by adamjcalhoun** [scikit-video/scikit-video#64]
Is there documentation somewhere on how to use inputdict/outputdict to read a movie? I am unsure what parameters I am supposed to be passing it, and I keep getting errors. I am reading an H264 .avi file...after figuring out that I need to pass '-s' with the frame dimensions, I get the following error:

Traceback (most recent call last):
  File "runFlyTracker.py", line 149, in <module>
    videodata = skvideo.io.FFmpegReader(movieName,{'-s':(str(width) + 'x' + str(height)).encode('asc
ii')})
  File "C:\Anaconda\lib\site-packages\skvideo\io\ffmpeg.py", line 153, in __init__
    if (str.encode(self.extension) in [b".raw", b".yuv"]):
TypeError: descriptor 'encode' requires a 'str' object but received a 'unicode'

...which I assume means that there are more parameters I need to pass in but what those are are somewhat opaque.

**Comment by beyondmetis** [comment]
Good suggestion. There should be documentation for some common inputdict/outputdict parameters. As for just reading an avi file, you shouldn't need any parameters.

Side note: the parameters that are passed as dicts get parsed then sent to the FFmpeg sub-process. That means that parameters are documented on the FFmpeg webpage, and you can always test the parameter behavior in the terminal separate from scikit-video through direct calls to ffmpeg.
