### ISSUE TITLE
cannot use 'VideoCapture'

### ISSUE THREAD

**Issue by shootingliu** [scikit-video/scikit-video#68]
Hello,

I have installed scikit-video by both of the two method,and also do 'sudo pip uninstall sk-video'.
But I always get <AttributeError: 'module' object has no attribute 'VideoCapture'>

Thanks in advance.

**Comment by beyondmetis** [comment]
I think that function was part of the old sk-video. We have plans to add a function like that back in, but don't have it yet. Check out the website for current API.

**Comment by shootingliu** [comment]
Hi,@beyondmetis,

Thanks,but could please tell me how can I find the old sk-video to install ?
