### ISSUE TITLE
import error: sk video is not found

### ISSUE THREAD

**Issue by shobamohan123** [scikit-video/scikit-video#71]
i have installed scikit video using the comment: pip install --user scikit-video. I got notification successfully installed. I installed in ananconda environment, python 2.7 and opencv version is 2.4.11. 
I used the following code in python to read video 
import skvideo.io  
videodata = skvideo.io.vread("car.avi")  
print(videodata.shape)
I got the error: ImportError: No module named skvideo.
Can anyone help me to overcome this error?

**Comment by shobamohan123** [comment]
I resolved the error by uninstalling scikit video then install using conda install -c conda-forge sk-video in anaconda prompt.

**Comment by beyondmetis** [comment]
This command should probably be conda install -c conda-forge scikit-video going forward.

**Comment by countkrusty** [comment]
I am currently encountering the same issue, but I installed scikit video using
`conda install -c conda-forge scikit-video`. It shows up in the installed packages when calling conda list (installed Version 1.1.11), but when trying to import it in the editor I get the `No module named 'skvideo'` error. 
I am using a PC with Windows 10 at the moment (I tried on my mac as well and don't have this issue)
Do you have any further suggestions?
