### ISSUE TITLE
VIIDEO score - Features arguments can't be changed

### ISSUE THREAD

**Issue by amarion35** [scikit-video/scikit-video#83]
Line 56 in `viideo.py`:

`features = viideo_features(videoData, blocksize=(18, 18), blockoverlap=(8, 8), filterlength=7)`

`blocksize`, `blockoverlap `and `filterlength `cannot be assigned to `viideo_features `in the `viideo_score `function.
Is it a mistake or it has be done on purpose?

**Comment by beyondmetis** [comment]
Definitely a mistake.

**Comment by beyondmetis** [comment]
Fixed and committed
