### ISSUE TITLE
numpy uint16 ndarray support

### ISSUE THREAD

**Issue by Lazare** [scikit-video/scikit-video#84]
Hi,

I have some videos with 10 bits per channel and don't want to lose the precision.
do you have plan to support reading video to numpy uint16 ndarray ?

If you are interested I have already a patch ready for this feature.

in pseudo code :

-------------------------------------------------------
for reader :
  if bpplut[pix_fmt][1]//bpplut[pix_fmt][0] == 16 :
    use dtype uint16 ('<u2' or '>u2' depending of endianess of the pix_fmt)
  else:
    do as usual

for writer :
  if pix_fmt is not set :
    if frame.dtype == uint16 ('<u2' or '>u2' in fact) :
      use a 16bit per channel format in _warmStart (taking endianess into account)
    else :
      do as usual
  else :
    if bpplut[pix_fmt][1]//bpplut[pix_fmt][0] == 16 :
    use dtype uint16 ('<u2' or '>u2' depending of endianess of the pix_fmt)
  else :
    do as usual

-------------------------------------------------------
The only backward compatibility issue would be for people using video writer with uint16 ndarray without specific input pix_fmt and using values between 0 and 255 as it would produce black videos. 
If that's a problem, a parameter 'allow16bits' which would default to false could be added in the writer __init__

**Comment by beyondmetis** [comment]
I suppose that we should close this?

**Comment by Lazare** [comment]
yes if course.

**Comment by wend1117** [comment]
I need the numpy uint16 ndarray support too, and I notice that this issue has been closed without a solution. Could you help me, sir?
